### ISSUE TITLE
react-transition-group-plus not actually required?

### ISSUE THREAD

**Issue by wldcordeiro** [nicolasdelfino/react-metro#1]
From reading your source it looks like it's never used so I don't think you need it to be a dependency. Also it'd be nice to know why you endorse it over react-transition-group

**Comment by nicolasdelfino** [comment]
Hi, @wldcordeiro you're right man! it's there from where Metro was born (codesandbox). I decided to go with plus cause it among other things allows interruptible transitions - though not implemented yet. 

It needs to be removed and docs needs an update to reflect that it's a peer dependency that the user needs to use Metro.

Would accept a pr if you're up for it. 
If not I'll do it as soon as I can.
