### ISSUE TITLE
How to unmount two components in a sequential animation?

### ISSUE THREAD

**Issue by jefflung** [nicolasdelfino/react-metro#15]
Hi Nicolas, thanks for your API, but I got a problem as mentioned in the title and I can't figure it out with your samples. Could you tell me how to do this? Thanks.

**Comment by nicolasdelfino** [comment]
Hi, I'm having a hard time understanding your question, Metro doesn't handle the actual unmounting of components - it only animates as a side effect when a mount / unmount hook gets triggered.

**Comment by jefflung** [comment]
Hi, sorry for my inadequate description. I have two components which enter a page in sequence. When a page has loaded, the first component appears and playing animation then fade out, and the second one fade in and stay on the page until the visitor goes to another page. Btw, I  appreciate your quick response sincerely, thanks.

**Comment by nicolasdelfino** [comment]
Sorry still not getting it. Please provide an image or link to a demo of what you're trying to achieve and we'll take it from there.

**Comment by nicolasdelfino** [comment]
@jefflung Closing this issue for now.
