### ISSUE TITLE
Creating a wrapper component for react-metro

### ISSUE THREAD

**Issue by dagda1** [nicolasdelfino/react-metro#9]
I want to create a generic wrapper component for animations, so I tried this:

```
import React, { Component } from 'react';
import Metro from 'react-metro';

export class TransitionComponent extends Component {
  props: Props;

  render() {
    const { children, show } = this.props;

    if (!show) {
      return null;
    }

    return Metro.container(
      <div>
        {children}
      </div>
    );
  }
}
```

And I would use it like this:

```
      <TransitionComponent transitionName="fade" show={props.show}>
        <MyComponent {...props} />
      </TransitionComponent>
```
But the animations are not being applied.

Is there something I am missing about rendering children like this?

**Comment by nicolasdelfino** [comment]
Hi @dagda1 You are probably just missing the transition group wrapper:
```javascript
<TransitionGroupPlus>
    <TransitionComponent transitionName="fade" show={props.show}>
      <MyComponent {...props} />
    </TransitionComponent>
</TransitionGroupPlus>
```

**Comment by dagda1** [comment]
Brilliant thanks, that was it.

If I wanted to use a slide transition, something like

```
.slide-appear {
  height: auto;
  max-height: 0;
  display: block;
  overflow: hidden;
  transition: max-height 500ms ease;
}
```
I should pass in a hash of values as the second argument to `Metro.container`, could you give me a pointer as to what I should be passing in for the max-height transition?

**Comment by nicolasdelfino** [comment]
Metro uses Greensock Tweenmax under the hood (specifically fromTo) so I suggest reading their docs at [https://greensock.com/docs/TweenMax/static.fromTo()]() and see what you might find out.

That being said it's important to know that Metro needs animation objects to function properly - apply in / out animations & execute the onMount / onUnmount callbacks.
